In [2]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
#1. Examples using TensorFlow
#scalar tensor
t1 = tf.constant(4)
print("Scalar Tensor: ")
print(t1)

Scalar Tensor: 
tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#vector tensor
t2 = tf.constant([1,5,10,15,20,25])
print("Vector Tensor: ")
print(t2)

Vector Tensor: 
tf.Tensor([ 1  5 10 15 20 25], shape=(6,), dtype=int32)


In [4]:
#matrix tensor
t3 = tf.constant([[1,5], [10,15], [20,25]])
print("Matrix Tensor: ")
print(t3)

Matrix Tensor: 
tf.Tensor(
[[ 1  5]
 [10 15]
 [20 25]], shape=(3, 2), dtype=int32)


In [5]:
#3D tensor
t4 = tf.constant([[[1,5], [10,15]], [[20,25], [30,35]]])
print("3D Tensor: ")
print(t4)

3D Tensor: 
tf.Tensor(
[[[ 1  5]
  [10 15]]

 [[20 25]
  [30 35]]], shape=(2, 2, 2), dtype=int32)


In [6]:
#zeros tensor
t5 = tf.zeros([3,3])
print("Zeros Tensor: ")
print(t5)

Zeros Tensor: 
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [7]:
#ones tensor
t6 = tf.ones([2,4])
print("Ones Tensor: ")
print(t6)

Ones Tensor: 
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


In [8]:
#matrix tensor
t7 = tf.constant([[2,4], [6,8], [10,12]])
print("Matrix Tensor: ")
print(t7)

Matrix Tensor: 
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)


In [9]:
#2.addition of 2D tensors
t_add = tf.add(t3, t7)
print("Added matrices t3 and t7: ")
print(t_add)

Added matrices t3 and t7: 
tf.Tensor(
[[ 3  9]
 [16 23]
 [30 37]], shape=(3, 2), dtype=int32)


In [11]:
#3.matrix operations using tensors


In [1]:
import tensorflow as tf